
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"   # UI de Jenkins
      - "50000:50000" # Agentes
    environment:
      - DOCKER_HOST=tcp://docker:2375  # Jenkins usar√° el Docker remoto (DinD)
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - docker

  docker: # Docker-in-Docker (DinD)
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=   # Desactiva TLS para usarlo sin certificados
    ports:
      - "2375:2375"
    volumes:
      - docker-data:/var/lib/docker

  web_html:
    image: nginx:latest
    container_name: web_html
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  jenkins_home:
  docker-data:
